### ISSUE TITLE
SaitamaRobot all fork this is a same problem ModuleNotFoundError: No module named 'spamwatch'

### ISSUE THREAD

**Issue by NetSHELL-Team** [AnimeKaizoku/SaitamaRobot#370]
[root@server SaitamaRobot]# python3 -m SaitamaRobot
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/SaitamaRobot/SaitamaRobot/__init__.py", line 5, in <module>
    import spamwatch
ModuleNotFoundError: No module named 'spamwatch'
[root@server SaitamaRobot]# 

SaitamaRobot all fork this is a same problem ModuleNotFoundError: No module named 'spamwatch'

**Comment by starry-shivam** [comment]
`pip install spamwatch` 
Just takes one google search tho..
