### ISSUE TITLE
Bug report userinfo.py line 232

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#376]
2021-02-11 10:10:29,382 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "E:\SaitamaRobot\env\lib\site-packages\telegram\utils\promise.py", line 56, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "E:\SaitamaRobot\SaitamaRobot\modules\userinfo.py", line 232, in info
    and not message.parse_entities([MessageEntity.TEXT_MENTION])
NameError: name 'MessageEntity' is not defined
1044879856

**Comment by Neppu-Nep** [comment]
Fixed in - 36a83cd7bbb98dff02c3215736b5b3f3d50a3709
