### ISSUE TITLE
Bug report self host problem centos7

### ISSUE THREAD

**Issue by NetSHELL-Team** [AnimeKaizoku/SaitamaRobot#393]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/saitama_co7/SaitamaRobot/__init__.py", line 183, in <module>
    from SaitamaRobot.modules.helper_funcs.handlers import (
  File "/root/saitama_co7/SaitamaRobot/modules/helper_funcs/handlers.py", line 1, in <module>
    import SaitamaRobot.modules.sql.blacklistusers_sql as sql
  File "/root/saitama_co7/SaitamaRobot/modules/sql/__init__.py", line 15, in <module>
    SESSION = start()
  File "/root/saitama_co7/SaitamaRobot/modules/sql/__init__.py", line 8, in start
    engine = create_engine(DB_URI, client_encoding="utf8")
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 341, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

self host
centos7
plese help anyone

**Comment by TsunayoshiSawada** [comment]
1. try shiken branch
2. make sure your db URL is valid
3. maybe just join @OnePunchDev on telegram (if you get stuck after trying above 2 points)

**Comment by NetSHELL-Team** [comment]
o thanks but i found sir this is sqlalchemyl & postgres version  problem
