### ISSUE TITLE
afk.py

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#420]
Ive just loaded the afk module but i keep hitting an error
Traceback (most recent call last):
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column afk_users.time does not exist
LINE 1: ...ers_is_afk, afk_users.reason AS afk_users_reason, afk_users....
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tgbot/tg/tg_bot/__main__.py", line 116, in <module>
    imported_module = importlib.import_module("tg_bot.modules." + module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tgbot/tg/tg_bot/modules/afk.py", line 11, in <module>
    from tg_bot.modules.sql import afk_sql as sql
  File "/home/tgbot/tg/tg_bot/modules/sql/afk_sql.py", line 97, in <module>
    __load_afk_users()
  File "/home/tgbot/tg/tg_bot/modules/sql/afk_sql.py", line 89, in __load_afk_users
    all_afk = SESSION.query(AFK).all()
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/tgbot/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column afk_users.time does not exist
LINE 1: ...ers_is_afk, afk_users.reason AS afk_users_reason, afk_users....
                                                             ^

[SQL: SELECT afk_users.user_id AS afk_users_user_id, afk_users.is_afk AS afk_users_is_afk, afk_users.reason AS afk_users_reason, afk_users.time AS afk_users_time
FROM afk_users]
(Background on this error at: http://sqlalche.me/e/13/f405)

Can anyone help?

**Comment by infinity-plus** [comment]
I had the same issue, clearing the database helps
As far as I know, it's because a new column needs to be added to the DB, that's `afk_user.time`

**Comment by ufoptg** [comment]
Should of posted awhile ago yes that is just what I did

**Comment by starry-shivam** [comment]
Add the missing column in your PostgreSQL database using:
```sql
ALTER TABLE afk_users ADD COLUMN time timestamptz;
```

**Comment by ufoptg** [comment]
All good I just Dropped the table and restarted process

**Comment by starry-shivam** [comment]
👍
