### ISSUE TITLE
fed_chats error in feds.py

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#431]
I have 101 chats in my federation when I type /fedchats i get this error 

`2021-06-26 21:39:16,697 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/utils/promise.py", line 56, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/tgbot/tg/SaitamaRobot/modules/helper_funcs/alternate.py", line 22, in command_func
    return func(update, context, *args, **kwargs)
  File "/home/tgbot/tg/SaitamaRobot/modules/feds.py", line 2072, in fed_chats
    chat_name = dispatcher.bot.getChat(chats).title
  File "/home/tgbot/.local/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/bot.py", line 2327, in get_chat
    result = self._request.post(url, data, timeout=timeout)
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 237, in _request_wrapper
    message = self._parse(resp.data)
  File "/home/tgbot/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 195, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 17 seconds`

**Comment by TsunayoshiSawada** [comment]
The updated source is private and includes a lot of fixes for feds and a whole lot more.

Unfortunately we do not provide support on issue requests on the public code anymore.
